name: build_OneDrive - T - erofs -test
on:
  workflow_dispatch:
    inputs:
      URL:
        description: "待操作的系统包下载地址"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device:
          - umi
    steps:
      - uses: actions/checkout@master
      - name: 1.准备环境
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          sudo apt install aria2
          aria2c -x16 -j$(nproc) -U "Mozilla/5.0" -d "$GITHUB_WORKSPACE" ${{ github.event.inputs.URL }}