name: Auto Pack

on:
  workflow_dispatch:
  push:
jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.get_update.outputs.result }}
    steps:
      - name: 检出仓库文件
        uses: actions/checkout@v4.1.7
      - name: 检测更新
        id: get_update
        run: |
          echo "result=false" >> $GITHUB_OUTPUT

  build:
    if: needs.check-version.outputs.result == 'true'
    runs-on: ubuntu-latest
    needs: check-version
    steps:
      - name: Hello
        run: |
          echo Hello
      - name: World
        run: |
          echo World