name: 建立缓存
on:
  # 自动触发
  schedule:
    - cron: "0 0 * * 0,1,4"
  # 手动触发  
  workflow_dispatch:
jobs:
  first_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device:
          - a
          - b
          - c
    steps:
      - name: 准备变量
        id: get-var
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          if [[ "$device" == "a" ]]; then
              echo "device=a" >> $GITHUB_OUTPUT
          elif [[ "$device" == "b" ]]; then
              echo "device=b" >> $GITHUB_OUTPUT
          elif [[ "$device" == "c" ]]; then
              echo "device=c" >> $GITHUB_OUTPUT
          fi
        env:
          device: ${{ matrix.device }}
      - name: 检查/下载缓存
        id: get-cache
        uses: actions/cache@main
        with:
          path: |
            ${{ steps.get-var.outputs.device }}
          key: ${{ steps.get-var.outputs.device }}
      # 若缓存存在则下载，否则将path中的内容上传至cache
      - if: ${{ steps.get-cache.outputs.cache-hit != 'true' }}
        uses: actions/checkout@master
      - if: ${{ steps.get-cache.outputs.cache-hit != 'true' }}
        name: 开始操作
        run: |
          echo 这里开始放你的脚本
          mkdir -p $GITHUB_WORKSPACE/$device
          touch $GITHUB_WORKSPACE/$device/test
          echo test > $GITHUB_WORKSPACE/$device/test
        env:
          device: ${{ matrix.device }}
      - if: ${{ steps.get-cache.outputs.cache-hit != 'true' }}
        name: 删除工作流运行
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
  # 两个job之间存储不互通，须走artifact
  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device:
          - a
          - b
          - c
    steps:
      - name: 准备变量
        id: get-var
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          if [[ "$device" == "a" ]]; then
              echo "device=a" >> $GITHUB_OUTPUT
          elif [[ "$device" == "b" ]]; then
              echo "device=b" >> $GITHUB_OUTPUT
          elif [[ "$device" == "c" ]]; then
              echo "device=c" >> $GITHUB_OUTPUT
          fi
        env:
          device: ${{ matrix.device }}
      - name: 检查/下载缓存
        id: get-cache
        uses: actions/cache@main
        with:
          path: |
            ${{ steps.get-var.outputs.device }}
          key: ${{ steps.get-var.outputs.device }}
        # 若缓存存在则下载，否则激昂path中的内容上传至cache
      - if: ${{ steps.get-cache.outputs.cache-hit != 'true' }}
        name: 开始操作
        run: |
          echo 这里开始放你的脚本
        env:
          device: ${{ matrix.device }}
      - if: ${{ steps.get-cache.outputs.cache-hit != 'true' }}
        name: 删除工作流运行
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
