name: CI
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      pan123:
        description: '123盘'
        required: true
        type: boolean
      OneDrive:
        description: 'OneDrive'
        required: true
        type: boolean
      GithubRelease:
        description: 'Github Release'
        required: true
        type: boolean
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ inputs.pan123 == 'true' }}
        name: test
        run: |
          echo "Log level: $LEVEL"
          echo "pan123: $pan123"
        env:
          LEVEL: ${{ inputs.logLevel }}
          pan123: ${{ inputs.pan123 }}
          OneDrive: ${{ inputs.OneDrive }}
          GithubRelease: ${{ inputs.GithubRelease }}
      - if: ${{ inputs.OneDrive == 'true' }}
        run: |
          echo "OneDrive: $OneDrive"
        env:
          LEVEL: ${{ inputs.logLevel }}
          pan123: ${{ inputs.pan123 }}
          OneDrive: ${{ inputs.OneDrive }}
          GithubRelease: ${{ inputs.GithubRelease }}
      - if: ${{ inputs.GithubRelease == 'true' }}
        run: |
          echo "GithubRelease: $GithubRelease"
        env:
          LEVEL: ${{ inputs.logLevel }}
          pan123: ${{ inputs.pan123 }}
          OneDrive: ${{ inputs.OneDrive }}
          GithubRelease: ${{ inputs.GithubRelease }}