name: get_a13_files
on:
  workflow_dispatch:
    inputs:
      URL:
        description: "待操作的系统包下载地址"
        required: true
      build_device:
        description: "底包机型代号"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 1.准备环境
        run: |
          echo "date=$(echo ${{ github.event.inputs.URL }} | cut -d"/" -f4)" >> $GITHUB_ENV
          sudo apt install python3 python3-pip aria2 zip p7zip-full tar zipalign zstd dos2unix
          sudo apt --fix-broken install
          sudo apt update --fix-missing
          pip3 install --upgrade pip
          pip3 install pycryptodome
          pip3 install setuptools
          pip3 install docopt
          pip3 install requests
          pip3 install beautifulsoup4
          pip3 install --ignore-installed pyyaml
      - name: 2.下载系统包
        run: |
          aria2c -x16 -j$(nproc) -U "Mozilla/5.0" -d "$GITHUB_WORKSPACE" ${{ github.event.inputs.URL }}
      - name: 3.检测payload/br
        run: |
          ZIP_NAME=$(echo ${{ github.event.inputs.URL }} | cut -d"/" -f5)
          7z x "$GITHUB_WORKSPACE"/$ZIP_NAME -r -o"$GITHUB_WORKSPACE"/MUNCH
          if [ -e "$GITHUB_WORKSPACE"/MUNCH/payload.bin ]; then
              echo "unpack=payload" >> $GITHUB_ENV
          else
              echo "unpack=br" >> $GITHUB_ENV
          fi
      - if: ${{ env.unpack == 'payload' }}
        name: 4/PL.解压payload
        run: |
          sudo chmod 777 "$GITHUB_WORKSPACE"/tools/payload-dumper-go
          sudo chmod 777 "$GITHUB_WORKSPACE"/tools/brotli
          sudo chmod 777 "$GITHUB_WORKSPACE"/tools/gettype
          sudo chmod 777 "$GITHUB_WORKSPACE"/tools/extract.erofs
          mkdir -p "$GITHUB_WORKSPACE"/"$device"
          mkdir -p "$GITHUB_WORKSPACE"/images/TI_config
          mkdir -p "$GITHUB_WORKSPACE"/get_a13_files
          ORIGIN_ZIP_NAME=$(echo ${{ github.event.inputs.URL }} | cut -d"/" -f5)
          md5sum "$GITHUB_WORKSPACE"/"$ORIGIN_ZIP_NAME"
          
          for i in vendor odm system product system_ext mi_ext; do
              "$GITHUB_WORKSPACE"/tools/payload-dumper-go -o "$GITHUB_WORKSPACE"/images/ -p $i "$GITHUB_WORKSPACE"/MUNCH/payload.bin
              if [[ $("$GITHUB_WORKSPACE"/tools/gettype -i "$GITHUB_WORKSPACE"/images/$i.img) == "ext" ]]; then
                  sudo python3 "$GITHUB_WORKSPACE"/tools/imgextractorLinux.py "$GITHUB_WORKSPACE"/images/$i.img "$GITHUB_WORKSPACE"/images
              elif [[ $("$GITHUB_WORKSPACE"/tools/gettype -i "$GITHUB_WORKSPACE"/images/$i.img) == "erofs" ]]; then
                  cd "$GITHUB_WORKSPACE"/images && "$GITHUB_WORKSPACE"/tools/extract.erofs -i "$GITHUB_WORKSPACE"/images/$i.img -x && cd "$GITHUB_WORKSPACE"
                  mv "$GITHUB_WORKSPACE"/images/config/* "$GITHUB_WORKSPACE"/images/TI_config
                  rm -rf "$GITHUB_WORKSPACE"/images/config
              fi    
              rm -rf "$GITHUB_WORKSPACE"/images/$i.img
          done
          "$GITHUB_WORKSPACE"/tools/payload-dumper-go -o "$GITHUB_WORKSPACE"/images/ -p modem "$GITHUB_WORKSPACE"/MUNCH/payload.bin
          sudo mv -f "$GITHUB_WORKSPACE"/images/* "$GITHUB_WORKSPACE"/"$device"
          sudo rm -rf "$GITHUB_WORKSPACE"/MUNCH
        env:
          device: ${{ github.event.inputs.build_device }}
      - if: ${{ env.unpack == 'br' }}
        name: 4/BR.解压br
        run: |
          sudo chmod 777 "$GITHUB_WORKSPACE"/tools/brotli
          mkdir -p "$GITHUB_WORKSPACE"/"$device"
          mkdir -p "$GITHUB_WORKSPACE"/images/TI_config
          mkdir -p "$GITHUB_WORKSPACE"/get_a13_files
          ORIGIN_ZIP_NAME=$(echo ${{ github.event.inputs.URL }} | cut -d"/" -f5)
          md5sum "$GITHUB_WORKSPACE"/"$ORIGIN_ZIP_NAME"
          for i in system odm system_ext product vendor mi_ext; do
              if [[ $i == mi_ext ]]; then
                  if [[ "$(7z l "$ORIGIN_ZIP_NAME" | grep mi_ext)" == "" ]]; then
                      break
                  else
                      touch "$GITHUB_WORKSPACE"/get_a13_files/has_mi_ext
                  fi
              fi
              7z x "$GITHUB_WORKSPACE"/"$ORIGIN_ZIP_NAME" -o"$GITHUB_WORKSPACE"/"$device" $i.transfer.list
              7z x "$GITHUB_WORKSPACE"/"$ORIGIN_ZIP_NAME" -o"$GITHUB_WORKSPACE"/"$device" $i.patch.dat
              7z x "$GITHUB_WORKSPACE"/"$ORIGIN_ZIP_NAME" -o"$GITHUB_WORKSPACE"/"$device" $i.new.dat.br
              "$GITHUB_WORKSPACE"/tools/brotli -d "$GITHUB_WORKSPACE"/"$device"/$i.new.dat.br
              rm -rf "$GITHUB_WORKSPACE"/"$device"/$i.new.dat.br
              python3 "$GITHUB_WORKSPACE"/tools/sdat2img.py "$GITHUB_WORKSPACE"/"$device"/$i.transfer.list "$GITHUB_WORKSPACE"/"$device"/$i.new.dat "$GITHUB_WORKSPACE"/"$device"/$i.img
              rm -rf "$GITHUB_WORKSPACE"/"$device"/$i.patch.dat
              rm -rf "$GITHUB_WORKSPACE"/"$device"/$i.transfer.list
              rm -rf "$GITHUB_WORKSPACE"/"$device"/$i.new.dat
              sudo python3 "$GITHUB_WORKSPACE"/tools/imgextractorLinux.py "$GITHUB_WORKSPACE"/"$device"/$i.img "$GITHUB_WORKSPACE"/"$device"
              rm -rf "$GITHUB_WORKSPACE"/"$device"/$i.img
          done
          rm -rf "$GITHUB_WORKSPACE"/"$ORIGIN_ZIP_NAME"
        env:
          device: ${{ github.event.inputs.build_device }}
      - name: 5.提取指定文件
        run: |
          for i in system odm system_ext product vendor mi_ext; do
            mkdir -p "$GITHUB_WORKSPACE"/get_a13_files/$i
          done
          sudo cp -f "$GITHUB_WORKSPACE"/"$device"/system/system/build.prop "$GITHUB_WORKSPACE"/get_a13_files/system
          sudo cp -f "$GITHUB_WORKSPACE"/"$device"/vendor/build.prop "$GITHUB_WORKSPACE"/get_a13_files/vendor
          sudo cp -f "$GITHUB_WORKSPACE"/"$device"/system_ext/etc/build.prop "$GITHUB_WORKSPACE"/get_a13_files/system_ext
          sudo cp -f "$GITHUB_WORKSPACE"/"$device"/product/etc/build.prop "$GITHUB_WORKSPACE"/get_a13_files/product
          sudo cp -f "$GITHUB_WORKSPACE"/"$device"/odm/etc/build.prop "$GITHUB_WORKSPACE"/get_a13_files/odm
          if [[ "$(7z l "$ORIGIN_ZIP_NAME" | grep mi_ext)" == "" ]]; then
              mkdir -p "$GITHUB_WORKSPACE"/get_a13_files/mi_ext
              mi_ext_build_prop=$(sudo find "$GITHUB_WORKSPACE"/"$device"/mi_ext -name "build.prop")
              sudo cp -f "$mi_ext_build_prop" "$GITHUB_WORKSPACE"/get_a13_files/mi_ext
          fi
          sudo 7z a "$GITHUB_WORKSPACE"/get_a13_files/selinux.zip "$GITHUB_WORKSPACE"/"$device"/vendor/etc/selinux
          sudo 7z a "$GITHUB_WORKSPACE"/get_a13_files/etc.zip "$GITHUB_WORKSPACE"/"$device"/vendor/etc/
          sudo 7z a "$GITHUB_WORKSPACE"/get_a13_files/overlay.zip "$GITHUB_WORKSPACE"/"$device"/product/overlay/*
          sudo 7z a "$GITHUB_WORKSPACE"/get_a13_files/pangu.zip "$GITHUB_WORKSPACE"/"$device"/product/pangu/
          sudo cp -rf "$GITHUB_WORKSPACE"/"$device"/product/etc/device_features/"$device".xml "$GITHUB_WORKSPACE"/get_a13_files
          sudo ls -l "$GITHUB_WORKSPACE"/"$device"/product/app/
          sudo cp -rf "$GITHUB_WORKSPACE"/"$device"/product/app/MiuiCit/MiuiCit.apk "$GITHUB_WORKSPACE"/get_a13_files
        env:
          device: ${{ github.event.inputs.build_device }}
      - name: 6.打包
        run: |
          mkdir -p "$GITHUB_WORKSPACE"/zip
          sudo chmod -R 777 "$GITHUB_WORKSPACE"/get_a13_files
          7z a "$GITHUB_WORKSPACE"/zip/"$device"_get_a13_files.zip "$GITHUB_WORKSPACE"/get_a13_files/*
          mv "$GITHUB_WORKSPACE"/zip/"$device"_get_a13_files.zip "$GITHUB_WORKSPACE"/zip/"$device"_"${{ env.date }}".zip
          cd "$GITHUB_WORKSPACE"
          touch file.log
          echo ""$device"_"${{ env.date }}".zip" > file.log
        env:
          device: ${{ github.event.inputs.build_device }}
      - name: 7.上传到Github Release
        uses: ncipollo/release-action@main
        with:
          artifacts: ${{ github.workspace }}/zip/*
          name: ${{ github.event.inputs.build_device }}_${{ env.date }}
          tag: ${{ github.event.inputs.build_device }}_${{ env.date }}
          bodyFile: "${{ github.workspace }}/file.log"
          allowUpdates: true
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: 8.删除工作流运行
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
