name: matrix1

on:
  workflow_dispatch:
    inputs:
      matrix-values: # 通过 inputs 定义矩阵的值，可以是逗号分隔的列表，也可以是字符串数组
        description: 'Comma-separated values for the matrix'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        value: ${{ fromJson(inputs.matrix-values) }} # 使用 fromJson 将输入的字符串转换为数组

    steps:
    - name: Print Matrix Value
      run: |
        echo "Matrix Value: ${{ matrix.value }}"
