name: build
on:
  push:
  workflow_dispatch:
    inputs:
      matrix-values:
        description: "matrix-values"
        default: "all"
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |          
          input_var="${{ github.event.inputs.matrix-values }}"            
          if [ "$input_var" = "865" ]; then
            input_var="umi,cmi,cas,apollo"
          elif [ "$input_var" = "870" ]; then
            input_var="thyme,alioth"
          else
            input_var="umi,cmi,cas,apollo,thyme,alioth"
          fi
          IFS=',' read -ra devices <<< "$input_var"
          json_output="{\"list\":["
          for device in "${devices[@]}"; do
            json_output+="{\"device\":\"$device\"},"
          done
          json_output=${json_output%,}
          json_output+="]}"
          json_output=$(echo $json_output | jq -c .)
          echo "matrix=$json_output" >> $GITHUB_OUTPUT
  job3:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ fromJSON(needs.job1.outputs.matrix) }}
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
      - run: |
          echo ${{ matrix.device }}
