name: build
on:
  push:
  workflow_dispatch:
    inputs:
      matrix-values:
        description: "matrix-values"
        type: string
        default: "all"
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          input_var="${{ github.event.inputs.matrix-values }}"
          if [ "$input_var" = "865" ]; then
            input_var="umi,cmi,cas,apollo"
          elif [ "$input_var" = "870" ]; then
            input_var="thyme,alioth"
          elif [ "$input_var" = "all" ]; then
            input_var="umi,cmi,cas,apollo,thyme,alioth"
          fi
          IFS=',' read -ra devices <<< "$input_var"
          json_output="{\"list\":["
          for device in "${devices[@]}"; do
            json_output+="{\"device\":\"$device\"},"
          done
          json_output=${json_output%,}
          json_output+="]}"
          echo "matrix=$json_output" >> $GITHUB_OUTPUT
      - name: 删除工作流运行
        uses: Mattraks/delete-workflow-runs@v2
        with:
            token: ${{ github.token }}
            repository: ${{ github.repository }}
            retain_days: 0
            keep_minimum_runs: 0
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
      - run: |
          echo "$MATRIX_CONTEXT" | jq -r '.list.device'
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
