name: matrix2
on:
  workflow_dispatch:
    inputs:
      matrix-values:
        description: "matrix-values"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{ github.event.inputs.matrix-values }}
    steps:
      - name: Print Matrix Value
        run: |
          echo "Matrix Value: ${{ matrix.value }}"

        