name: test
on:
  workflow_dispatch:
jobs:
  setup-matrix:
    runs-on: ubuntu-18.04
    steps:
      - name: Check Support FileSystems
        run: |
          cat /proc/filesystems
          uname -r