name: test
on:
  workflow_dispatch:
jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Write Github_ENV
        run: |
          pip3 install pycryptodome
          pip3 install requests