name: test
on:
  workflow_dispatch:
jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Write Github_ENV
        run: |
          echo "zjw=20030721" >> $GITHUB_ENV
      - name: Test Github_ENV
        run: |
          echo "$zjw"
      - name: Test Github_ENV Again
        run: |
          echo "${{ env.zjw }}"
      - name: Test Github_ENV Third
        run: |
          echo "$zjw2"
        env:
          zjw2: ${{ env.zjw }}
      - name: Test Github_ENV Third
        run: |
          echo "$zjw3"
        env:
          zjw3: $zjw
