name: test
on:
  workflow_dispatch:
jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Write Github_ENV
        run: |
          RANDOMSEED=$(tr -dc 'a-f0-9' < /dev/urandom | head -c 16)
          echo "RANDOMSEED=0x$RANDOMSEED"