name: test
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Write Github_ENV
        run: |
          pip3 install pycryptodome
          pip3 install requests
          device=ishtar
          python3 "$GITHUB_WORKSPACE"/XiaomiUpdateInfo.py $device V14.0.20.0.TMACNXM 13
