name: test
on:
  workflow_dispatch:
jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Write Github_ENV
        run: |
          sudo bash $GITHUB_WORKSPACE/tools/install.sh $GITHUB_WORKSPACE
