name: test
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  pre-get:
    name: Pre-Build Task
    runs-on: ubuntu-latest
    outputs: 
      URL: ${{ steps.generate_url.outputs.URL }}
    steps:
      - name: Check out code
        uses: actions/checkout@main
      - name: Generate URL
        id: generate_url
        run: |
          pip3 install pycryptodome
          pip3 install requests
          device=ishtar
          echo "URL=$(python3 "$GITHUB_WORKSPACE"/XiaomiUpdateInfo.py $device V14.0.20.0.TMACNXM 13)" >> "$GITHUB_OUTPUT"
  get-URL:
    name: Get URL
    runs-on: ubuntu-latest
    needs: pre-get
    strategy:
      matrix:
        device_type: ["umi", "cmi", "cas", "apollo"]
    steps:
      - name: Check out code
        uses: actions/checkout@main
      - name: Read URL.txt
        run: |
          echo "URL: $(cat URL.txt)"
        env: 
          URL: ${{needs.pre-get.outputs.URL}}
      - name: Compile Devices
        run: |
          echo "Compiling for device $DEVICE_TYPE using URL.txt: $(cat URL.txt)"
        env:
          DEVICE_TYPE: ${{ matrix.device_type }}
          URL: ${{needs.pre-get.outputs.URL}}

