name: 融合版
on:
  workflow_dispatch:
    inputs:
      URL:
        description: "待操作的系统包下载地址"
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        device:
          - umi
          - cmi
          - cas
    steps:
      - uses: actions/checkout@master
      - name: 1.准备环境
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          echo "origin_date=$(echo ${{ github.event.inputs.URL }} | cut -d"/" -f4)" >> $GITHUB_ENV
          if [ -n "${{ github.event.inputs.custom_version }}" ]; then
              echo "date=${{ github.event.inputs.custom_version }}" >> $GITHUB_ENV
          else
              echo "date=$(echo ${{ github.event.inputs.URL }} | cut -d"/" -f4)" >> $GITHUB_ENV
          fi
          echo "host=$(uname -n)" >> $GITHUB_ENV
          if [[ "$device" == "umi" ]]; then
              echo "device=umi" >> $GITHUB_ENV
              ORIGIN_URL=https://hugeota.d.miui.com/V14.0.2.0.TJBCNXM/miui_UMI_V14.0.2.0.TJBCNXM_6d38dfc521_13.0.zip
          elif [[ "$device" == "cmi" ]]; then
              echo "device=cmi" >> $GITHUB_ENV
              ORIGIN_URL=https://hugeota.d.miui.com/V14.0.2.0.TJACNXM/miui_CMI_V14.0.2.0.TJACNXM_40bb8418f6_13.0.zip
          elif [[ "$device" == "cas" ]]; then
              echo "device=cas" >> $GITHUB_ENV
              ORIGIN_URL=https://hugeota.d.miui.com/V14.0.1.0.TJJCNXM/miui_CAS_V14.0.1.0.TJJCNXM_8ff78bbc57_13.0.zip
          fi
          echo "ORIGIN_URL=$ORIGIN_URL" >> $GITHUB_ENV
          echo "ORIGIN_ZIP_NAME=$(echo $ORIGIN_URL | cut -d"/" -f5)
        env:
          device: ${{ matrix.device }}