name: test_123
on:
  workflow_dispatch:
jobs:
  pan123_upload:
    name: 上传到123盘
    runs-on: ubuntu-latest
    steps:
      - name: 发送开始构建通知
        run: |
          echo "device=ishtar" >> "$GITHUB_ENV"
      - name: 下载 TWRP
        uses: robinraju/release-downloader@v1.9
        with:
            repository: zjw2017/TWRP_Backup
            tag: "twrp"
            fileName: "*${{ env.device }}*"
            out-file-path: "${{ env.device }}_files"
            token: ${{ secrets.GH_TOKEN }}
      - name: ls -l
        run: |
          ls -l ./$device_files
