name: test
on:
  push:
  workflow_dispatch:
jobs:
  pan123_upload:
    name: 上传到123盘
    runs-on: ubuntu-latest
    steps:
      - name: 合并分卷并上传
        run: |
          ping open-api.123pan.com
          