name: test
on:
  workflow_dispatch:
jobs:
  accessToken_update:
    name: 更新 accessToken
    runs-on: ubuntu-latest
    outputs:
      accessToken: ${{ steps.export_accessToken.outputs.accessToken }}
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          repository: Weverses/ActionBuildCasSystemT
          token: ${{ secrets.GH_TOKEN }}
          sparse-checkout: |
            tools/123pan_info.txt
          sparse-checkout-cone-mode: false
      - name: 更新 accessToken
        id: export_accessToken
        run: |
          clientID="${{ secrets.CLIENTID }}"
          clientSecret="${{ secrets.CLIENTSECRET }}"
          source "$GITHUB_WORKSPACE"/tools/123pan_info.txt
          current_timestamp=$(date +%s)
          expired_timestamp=$(date -d "$expiredAt" +%s)
          if [ "$current_timestamp" -lt "$expired_timestamp" ]; then
            echo "access_token 未过期"
          else
            echo "access_token 已过期"
            post_context=$(
              curl -X POST \
                -H "Content-Type: application/json" \
                -H "Platform: open_platform" \
                -d "{
                  \"clientID\": \"$clientID\",
                  \"clientSecret\": \"$clientSecret\"
                }" \
                "https://open-api.123pan.com/api/v1/access_token"
            )
            accessToken=$(echo $post_context | jq -r .data.accessToken)
            expiredAt=$(echo $post_context | jq -r .data.expiredAt)
            echo "accessToken=\"$accessToken\"" >"$GITHUB_WORKSPACE"/tools/123pan_info.txt
            echo "expiredAt=\"$expiredAt\"" >>"$GITHUB_WORKSPACE"/tools/123pan_info.txt
            git config --global user.email "30484319+zjw2017@users.noreply.github.com"
            git config --global user.name "柚稚的孩纸"
            git add "$GITHUB_WORKSPACE"/tools/123pan_info.txt
            git commit -m "更新 accessToken"
            git push
          fi
          echo "accessToken=$accessToken" >> "$GITHUB_OUTPUT"
  pan123_upload:
    name: 上传到123盘
    runs-on: ubuntu-latest
    needs: accessToken_update
    steps:
      - name: echo
        run: |
          echo $accessToken
        env:
          accessToken: ${{ needs.accessToken_update.outputs.accessToken }}
      - name: 删除工作流运行
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
