name: miui rom下载
on:
  workflow_dispatch:
    inputs:
      URL:
        description: "下载地址"
        required: true
        type: string
jobs:
  build:
    name: 下载ROM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 准备 Rclone
        run: |
          sudo bash "$GITHUB_WORKSPACE"/tools/install_rclone.sh ${{ secrets.GH_TOKEN }}
          mkdir -p ~/.config/rclone/
          unzip -o -q -P ${{ secrets.PASSWORD }} "$GITHUB_WORKSPACE"/tools/rclone_config.zip -d ~/.config/rclone/
      - name: 下载系统包
        run: |
          sudo apt-get install aria2
          mkdir zip
          aria2c -x16 -j$(nproc) -U "Mozilla/5.0" -d "$GITHUB_WORKSPACE"/zip "$URL"
        env:
          URL: ${{ inputs.URL }}
      - name: 上传到OneDrive
        run: |
          rclone mkdir OneDrive:/Offline_Download
          rclone copy -P ./zip/* OneDrive:/Offline_Download --buffer-size=1024M