name: Xiaomi HyperOS
on:
  workflow_dispatch:
    inputs:
      build_matrix:
        description: "构建阵列，以英文逗号分隔，预置all,865和870"
        type: string
        default: "865"
        required: true
      INFO:
        description: "待操作的系统代号(小写)和版本号和安卓版本号(以英文逗号分隔)或直接输入下载链接"
        required: true
        type: string
      custom_version:
        description: "待打包的版本号"
        required: true
        type: string
      pack_version:
        description: "待打包的类型"
        required: true
        default: "premium"
        type: choice
        options:
          - premium
          - free
          - PedroZ
      VK:
        description: "Voyager Kernel"
        required: true
        type: boolean
        default: true
      data:
        description: "去除data加密"
        required: true
        type: boolean
        default: false
      pack_type:
        description: "待打包的系统分区格式和上传方式"
        required: true
        default: "erofs"
        type: choice
        options:
          - erofs
          - ext4
      OneDrive:
        description: "OneDrive"
        required: true
        type: boolean
        default: true
      GithubRelease:
        description: "Github Release"
        required: true
        type: boolean
        default: true
      pan123:
          description: "123盘"
          required: true
          type: boolean
          default: true 
jobs:
  url-get:
    name: 下载链接获取
    runs-on: ubuntu-latest
    outputs:
      URL: ${{ steps.generate_url.outputs.URL }}
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          repository: Weverses/ActionBuildCasSystemT
          token: ${{ secrets.GH_TOKEN }}
          sparse-checkout: |
            cookies.json
            tools/python/XiaomiUpdateInfo.py
          sparse-checkout-cone-mode: false
      - name: 下载链接获取
        id: generate_url
        run: |
          if [[ "$INFO" == *http* ]]; then
            echo "URL=$(echo $INFO)" >> "$GITHUB_OUTPUT"
          else
            sudo apt-get install python3
            pip3 install pycryptodome
            pip3 install requests
            target_device=$(echo $INFO | cut -d"," -f1)
            target_version=$(echo $INFO | cut -d"," -f2)
            target_android_version=$(echo $INFO | cut -d"," -f3)
            URL=$(python3 "$GITHUB_WORKSPACE"/tools/python/XiaomiUpdateInfo.py $target_device $target_version $target_android_version)
            echo "URL=$(echo $URL | grep -oP 'download: \K\S+')" >> "$GITHUB_OUTPUT"
          fi
        env:
          INFO: ${{ inputs.INFO }}
  build_matrix:
    name: 设置构建阵列
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: 设置构建阵列
        id: set-matrix
        run: |   
          input_var="${{ github.event.inputs.build_matrix }}"
          if [ "$input_var" = "865" ]; then
            input_var="umi,cmi,cas,apollo"
          elif [ "$input_var" = "870" ]; then
            input_var="thyme,alioth"
          elif [ "$input_var" = "all" ]; then
            input_var="umi,cmi,cas,apollo,thyme,alioth"
          fi
          IFS=',' read -ra devices <<< "$input_var"
          json_output="{\"list\":["
          for device in "${devices[@]}"; do
            json_output+="{\"device\":\"$device\"},"
          done
          json_output=${json_output%,}
          json_output+="]}"
          echo "matrix=$json_output" >> $GITHUB_OUTPUT
  build:
    name: 自动构建
    runs-on: ubuntu-latest
    needs: [url-get, build_matrix]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.build_matrix.outputs.matrix) }}
    steps:
      - name: 精简无用组件
        run: |
          docker rmi `docker images -q` || true
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d || true
          sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* || true
          sudo apt -y autoremove --purge || true
          sudo apt -y autoclean || true
          sudo apt clean || true
      - name: 最大化并挂载构建空间
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 1024
          swap-size-mb: 6144
          remove-dotnet: "true"
          temp-reserve-mb: 1024
          remove-android: "true"
          remove-haskell: "true"
      - uses: actions/checkout@v4.1.1
        with:
          repository: Weverses/ActionBuildCasSystemT
          token: ${{ secrets.GH_TOKEN }}
      - name: 发送开始构建通知
        run: |
          device=$(echo "$MATRIX_CONTEXT" | jq -r '.list.device')
          date=$custom_version
          if [[ "$device" == "umi" ]]; then
            curl -i -X POST -H 'Content-type':'application/json' -d '{"token":"${{ secrets.appToken2 }}","title":"小米10 '"$date"'开始构建","content":" **小米10 '"$date"'开始构建** ","topic":"umi","template":"markdown"}' http://www.pushplus.plus/send || true
          elif [[ "$device" == "cmi" ]]; then
            curl -i -X POST -H 'Content-type':'application/json' -d '{"token":"${{ secrets.appToken2 }}","title":"小米10Pro '"$date"'开始构建","content":" **小米10Pro '"$date"'开始构建** ","topic":"cmi","template":"markdown"}' http://www.pushplus.plus/send || true
          elif [[ "$device" == "cas" ]]; then
            curl -i -X POST -H 'Content-type':'application/json' -d '{"token":"${{ secrets.appToken2 }}","title":"小米10 Ultra '"$date"'开始构建","content":" **小米10 Ultra '"$date"'开始构建** ","topic":"cas","template":"markdown"}' http://www.pushplus.plus/send || true
          elif [[ "$device" == "apollo" ]]; then
            curl -i -X POST -H 'Content-type':'application/json' -d '{"token":"${{ secrets.appToken2 }}","title":"红米K30S Ultra '"$date"'开始构建","content":" **红米K30S Ultra '"$date"'开始构建** ","topic":"cas","template":"markdown"}' http://www.pushplus.plus/send || true
          elif [[ "$device" == "thyme" ]]; then
            curl -i -X POST -H 'Content-type':'application/json' -d '{"token":"${{ secrets.appToken2 }}","title":"小米10S '"$date"'开始构建","content":" **小米10S '"$date"'开始构建** ","topic":"umi","template":"markdown"}' http://www.pushplus.plus/send || true
          elif [[ "$device" == "alioth" ]]; then
            curl -i -X POST -H 'Content-type':'application/json' -d '{"token":"${{ secrets.appToken2 }}","title":"红米K40 '"$date"'开始构建","content":" **红米K40 '"$date"'开始构建** ","topic":"cmi","template":"markdown"}' http://www.pushplus.plus/send || true
          fi
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
          custom_version: ${{ inputs.custom_version }}
      - name: 下载系统包
        run: |
          device=$(echo "$MATRIX_CONTEXT" | jq -r '.list.device')
          sudo apt-get install python3 aria2 p7zip-full zstd unzip zipalign
          sudo bash "$GITHUB_WORKSPACE"/tools/install_rclone.sh ${{ secrets.GH_TOKEN }}
          mkdir -p ~/.config/rclone/
          unzip -o -q -P ${{ secrets.PASSWORD }} "$GITHUB_WORKSPACE"/tools/rclone_config.zip -d ~/.config/rclone/
          if [[ "$device" == "umi" ]]; then
            ORIGIN_URL=https://hugeota.d.miui.com/V14.0.4.0.TJBCNXM/miui_UMI_V14.0.4.0.TJBCNXM_23fc5ef4ee_13.0.zip
          elif [[ "$device" == "cmi" ]]; then
            ORIGIN_URL=https://hugeota.d.miui.com/V14.0.4.0.TJACNXM/miui_CMI_V14.0.4.0.TJACNXM_dd66e9703f_13.0.zip
          elif [[ "$device" == "cas" ]]; then
            ORIGIN_URL=https://hugeota.d.miui.com/V14.0.2.0.TJJCNXM/miui_CAS_V14.0.2.0.TJJCNXM_8064d8e1fb_13.0.zip
          elif [[ "$device" == "apollo" ]]; then
            ORIGIN_URL=https://hugeota.d.miui.com/V14.0.5.0.SJDCNXM/miui_APOLLO_V14.0.5.0.SJDCNXM_e727f2446b_12.0.zip
          elif [[ "$device" == "thyme" ]]; then
            ORIGIN_URL=https://hugeota.d.miui.com/V14.0.6.0.TGACNXM/miui_THYME_V14.0.6.0.TGACNXM_a3c1d41b17_13.0.zip
          elif [[ "$device" == "alioth" ]]; then
            ORIGIN_URL=https://hugeota.d.miui.com/V14.0.8.0.TKHCNXM/miui_ALIOTH_V14.0.8.0.TKHCNXM_50141f32f2_13.0.zip
          fi
          ORIGIN_ZIP_NAME=$(echo $ORIGIN_URL | sed 's/.*\(miui_.*\.zip\).*/\1/')
          ZIP_NAME_TARGET=$(echo $URL | sed 's/.*\(miui_.*\.zip\).*/\1/')
          rclone copy OneDrive:/MI_Packages/RubbishBin/BottomPackages/"$ORIGIN_ZIP_NAME" "$GITHUB_WORKSPACE"
          if [[ "$URL" == *PrePackages* ]]; then
            rclone copy OneDrive:/MI_Packages/RubbishBin/PrePackages/"$ZIP_NAME_TARGET" "$GITHUB_WORKSPACE"
          elif [[ "$URL" != "$ORIGIN_URL" ]]; then
            aria2c -x16 -j$(nproc) -U "Mozilla/5.0" -d "$GITHUB_WORKSPACE" "$URL"
          fi
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
          URL: ${{ needs.url-get.outputs.URL }}
      - name: 自动构建
        run: |
          device=$(echo "$MATRIX_CONTEXT" | jq -r '.list.device')
          bash build_local.sh $URL $device $custom_version $pack_version $VK $data $pack_type
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
          URL: ${{ needs.url-get.outputs.URL }}
          custom_version: ${{ inputs.custom_version }}
          pack_version: ${{ inputs.pack_version }}
          VK: ${{ inputs.VK }}
          data: ${{ inputs.data }}
          pack_type: ${{ inputs.pack_type }}
      - if: ${{ github.event.inputs.GithubRelease == 'true' }}
        name: 处理包
        run: |
          source "$GITHUB_WORKSPACE"/PackageInfo.txt
          echo "MD5=$MD5" >> "$GITHUB_ENV"
          echo "NEW_PACKAGE_NAME=$NEW_PACKAGE_NAME" >> "$GITHUB_ENV"
          mkdir -p "$GITHUB_WORKSPACE"/GithubRelease
          cd "$GITHUB_WORKSPACE"/GithubRelease
          sudo split -b 1536M -d "$GITHUB_WORKSPACE"/zip/"$NEW_PACKAGE_NAME" "$NEW_PACKAGE_NAME"
          cd "$GITHUB_WORKSPACE"
          touch file.log
          echo "$NEW_PACKAGE_NAME" > file.log
      - if: ${{ github.event.inputs.GithubRelease == 'true' }}
        name: 上传到Github Release
        uses: ncipollo/release-action@main
        with:
          artifacts: ${{ github.workspace }}/GithubRelease/*
          name: "${{ inputs.custom_version }}"
          tag: "${{ inputs.custom_version }}"
          bodyFile: "${{ github.workspace }}/file.log"
          allowUpdates: true
          artifactErrorsFailBuild: true
      - if: ${{ github.event.inputs.OneDrive == 'true' }}
        name: 上传到OneDrive
        run: |
          rclone mkdir OneDrive:/MI_Packages/RubbishBin/DevPackages
          rclone copy -P ./zip/* OneDrive:/MI_Packages/RubbishBin/DevPackages --buffer-size=1024M
      - if: ${{ github.event.inputs.pan123 == 'true' }}
        name: 上传到123盘
        run: |
          python3 "$GITHUB_WORKSPACE"/tools/python/123pan.py ${{ secrets.CLIENTID }} ${{ secrets.CLIENTSECRET }} 3646399 "$GITHUB_WORKSPACE"/zip/"$NEW_PACKAGE_NAME"
      - name: 发送打包成功通知
        run: |
          if [[ "$device" == "umi" ]]; then
            curl -i -X POST -H 'Content-type':'application/json' -d '{"token":"${{ secrets.appToken2 }}","title":"小米10 '"$date"'已构建完成","content":" **小米10 '"$date"'已构建完成** \n \n **包名：'"$NEW_PACKAGE_NAME"'** \n \n **MD5：'"$MD5"'** \n \n **下载地址为：[https://onedrive.zjw.js.cn/RubbishBin/DevPackages/'"$NEW_PACKAGE_NAME"'](https://onedrive.zjw.js.cn/RubbishBin/DevPackages/'"$NEW_PACKAGE_NAME"')** ","topic":"umi","template":"markdown"}' http://www.pushplus.plus/send || true
          elif [[ "$device" == "cmi" ]]; then
            curl -i -X POST -H 'Content-type':'application/json' -d '{"token":"${{ secrets.appToken2 }}","title":"小米10Pro '"$date"'已构建完成","content":" **小米10Pro '"$date"'已构建完成** \n \n **包名：'"$NEW_PACKAGE_NAME"'** \n \n **MD5：'"$MD5"'** \n \n **下载地址为：[https://onedrive.zjw.js.cn/RubbishBin/DevPackages/'"$NEW_PACKAGE_NAME"'](https://onedrive.zjw.js.cn/RubbishBin/DevPackages/'"$NEW_PACKAGE_NAME"')** ","topic":"cmi","template":"markdown"}' http://www.pushplus.plus/send || true
          elif [[ "$device" == "cas" ]]; then
            curl -i -X POST -H 'Content-type':'application/json' -d '{"token":"${{ secrets.appToken2 }}","title":"小米10 Ultra '"$date"'已构建完成","content":" **小米10 Ultra '"$date"'已构建完成** \n \n **包名：'"$NEW_PACKAGE_NAME"'** \n \n **MD5：'"$MD5"'** \n \n **下载地址为：[https://onedrive.zjw.js.cn/RubbishBin/DevPackages/'"$NEW_PACKAGE_NAME"'](https://onedrive.zjw.js.cn/RubbishBin/DevPackages/'"$NEW_PACKAGE_NAME"')** ","topic":"cas","template":"markdown"}' http://www.pushplus.plus/send || true
          elif [[ "$device" == "apollo" ]]; then
            curl -i -X POST -H 'Content-type':'application/json' -d '{"token":"${{ secrets.appToken2 }}","title":"红米K30S Ultra '"$date"'已构建完成","content":" **红米K30S Ultra '"$date"'已构建完成** \n \n **包名：'"$NEW_PACKAGE_NAME"'** \n \n **MD5：'"$MD5"'** \n \n **下载地址为：[https://onedrive.zjw.js.cn/RubbishBin/DevPackages/'"$NEW_PACKAGE_NAME"'](https://onedrive.zjw.js.cn/RubbishBin/DevPackages/'"$NEW_PACKAGE_NAME"')** ","topic":"cas","template":"markdown"}' http://www.pushplus.plus/send || true
          elif [[ "$device" == "thyme" ]]; then
            curl -i -X POST -H 'Content-type':'application/json' -d '{"token":"${{ secrets.appToken2 }}","title":"小米10S '"$date"'已构建完成","content":" **小米10S '"$date"'已构建完成** \n \n **包名：'"$NEW_PACKAGE_NAME"'** \n \n **MD5：'"$MD5"'** \n \n **下载地址为：[https://onedrive.zjw.js.cn/RubbishBin/DevPackages/'"$NEW_PACKAGE_NAME"'](https://onedrive.zjw.js.cn/RubbishBin/DevPackages/'"$NEW_PACKAGE_NAME"')** ","topic":"umi","template":"markdown"}' http://www.pushplus.plus/send || true
          elif [[ "$device" == "alioth" ]]; then
            curl -i -X POST -H 'Content-type':'application/json' -d '{"token":"${{ secrets.appToken2 }}","title":"红米K40 '"$date"'已构建完成","content":" **红米K40 '"$date"'已构建完成** \n \n **包名：'"$NEW_PACKAGE_NAME"'** \n \n **MD5：'"$MD5"'** \n \n **下载地址为：[https://onedrive.zjw.js.cn/RubbishBin/DevPackages/'"$NEW_PACKAGE_NAME"'](https://onedrive.zjw.js.cn/RubbishBin/DevPackages/'"$NEW_PACKAGE_NAME"')** ","topic":"cmi","template":"markdown"}' http://www.pushplus.plus/send || true
          fi
      - name: 删除工作流运行
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
